# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

org: ashokb08
app: headlines-tweet-app
service: headlines-tweet-bot

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  profile: sls-admin
  region: ap-south-1
  lambdaHashingVersion: 20201221
  environment:
    TWITTER_SECRETS_BUCKET: "my-twitter-secrets-bucket"
    FILE_NAME: "twitter_creds.json"
    S3_REGION: "ap-south-1"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:ListBucket
      Resource: "arn:aws:s3:::${self:provider.environment.TWITTER_SECRETS_BUCKET}"
    - Effect: Allow
      Action:
        - s3:*Object
      Resource: "arn:aws:s3:::${self:provider.environment.TWITTER_SECRETS_BUCKET}/*"

functions:
  hello:
    handler: handler.hello
    events:
      - schedule:
          enabled: true
          name: TheHinduTopHeadlinesTweetEventRule
          description: 'Every 10 minutes headlines from the hindu'
          rate: cron(0/5 * * * ? *)
          input:
            source: 'the-hindu'
      - schedule:
          enabled: true
          name: TOIHeadlinesTweetEventRule
          description: 'Every 30 minutes headlines from the times of india'
          rate: cron(0/5 * * * ? *)
          input:
            source: 'the-times-of-india'
plugins:
  - serverless-python-requirements
  - serverless-local-schedule
